# Generated by Django 3.0.6 on 2020-05-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('about_company', models.TextField(blank=True)),
                ('c9lcust_feedback', models.CharField(max_length=200)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
